apiVersion: v1
kind: Pod
metadata:
  name: website
  labels:
    app: website

spec:
  restartPolicy: Always
  containers:
    - name: front-end
      image: ghcr.io/tim-van-oudheusden/website/front-end:latest
      env:
        - name: NODE_ENV
          value: production
      ports:
        - containerPort: 3000
          hostPort: 3000

    - name: back-end
      image: ghcr.io/tim-van-oudheusden/website/back-end:latest
      env:
        - name: NODE_ENV
          value: production
        - name: HOST
          value: "0.0.0.0"
      ports:
        - containerPort: 3001
          hostPort: 3001