import type { HomeSectionDefinition } from "../types/home-section";

export const HOME_SECTIONS: HomeSectionDefinition[] = [
  {
    id: "hero",
    label: "home",
    heading: "Reboot With Me",
    body: "A new-age way of saying: getting your life back on track. The core principle of the website and project, unfolding in various ways.",
    bgColor: "var(--adw-accent-blue)",
    bgImage: "/images/wave-blue.svg",
    ctaLabel: "Discover",
    ctaTargetId: "value-pillars",
    contentDirection: "column",
  },
  {
    id: "value-pillars",
    label: "for you",
    heading: "Why this project exists",
    body: "Placeholder pillar block for concise statements that explain product value.",
    bgColor: "var(--adw-accent-teal)",
    bgImage: "/images/gradient-teal.svg",
    contentDirection: "row",
  },
  {
    id: "feature-strips",
    label: "for devs",
    heading: "Core capabilities at a glance",
    body: "Placeholder alternating feature rows for visuals, highlights, and context.",
    bgColor: "var(--adw-accent-green)",
    bgImage: "/images/wave-green.svg",
    contentDirection: "row",
  },
  {
    id: "proof",
    label: "conquer",
    heading: "Evidence and ecosystem trust",
    body: "Placeholder trust block for metrics, testimonials, and compatibility notes.",
    bgColor: "var(--adw-accent-orange)",
    bgImage: "/images/gradient-orange.svg",
    contentDirection: "column",
  },
  {
    id: "community-and-docs",
    label: "strengthen",
    heading: "Get help and follow updates",
    body: "Placeholder links to documentation, community channels, and release notes.",
    bgColor: "var(--adw-accent-purple)",
    bgImage: "/images/wave-purple.svg",
    contentDirection: "row",
  },
  {
    id: "secondary-cta",
    label: "independence",
    heading: "Ready to dive deeper",
    body: "Placeholder conversion block before footer with secondary action options.",
    bgColor: "var(--adw-accent-pink)",
    bgImage: "/images/gradient-pink.svg",
    contentDirection: "column",
  },
  {
    id: "footer",
    label: "inner peace",
    heading: "Everything else",
    body: "Placeholder footer surface for legal pages, social links, and contact paths.",
    bgColor: "var(--adw-accent-slate)",
    bgImage: "/images/wave-slate.svg",
    contentDirection: "column",
  },
];
